build: Avoid overriding user source directories
When synchronizing repos, avoid overriding unsaved changes. We retain
most of the existing behavior by default:

1. Try to checkout the given revision. If it's already checked out, do
   nothing.

2. Otherwise try to fetch it from the remote and check it out.

3. But if the checkout would override unsaved changes in the local
   source dir, refuse the update the source directory and display an
   error:

      error: The following untracked working tree files would be overwritten by checkout:
      	some-file
      Please move or remove them before you switch branches.
      note: use --force-sync=tfa to override any change

With --force-sync=<component> or --force-sync-all, we fetch the given
revision from the remote, and force apply it, discarding any unsaved
changes. This also allows to fetch updates from the remote branch.

Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>